/**
 * library-builder.js — the filesystem counterpart of the rubric
 * (Forest Builder Stage 1A, FOREST-BUILDER-KIT-MATCHER.md §4.5; LIBRARY-BUILDER.md).
 *
 * A background concern of ingest, NOT a one-time migration: each part handed in
 * is PLACED canonically under public/library/<partTree>/<rubricValue>/<id>/ with
 * a paired meta.json (tags + conformReport + source), and MANIFEST.json is
 * regenerated. Converges the on-disk mess (split leaves / opaque Bark0NN / flat
 * 241-chassis pile) toward "one canonical folder per part-type, named by rubric
 * value, never vendor id" — incrementally, only for parts touched, never blocking.
 *
 * Stage-1 scope decision (documented): we place the canonical META + a sourcePath
 * POINTER, and do NOT duplicate binaries by default (241 GLBs + bark texture sets
 * would bloat the repo for zero matcher benefit — the matcher reads tags, not
 * pixels). opts.copyBinaries copies the small leaf shape.png. Binary relocation
 * is the incremental follow-on (§4.5 "never a blocking migration"). The Builder
 * owns the indirection: sourcePath keeps every reference valid.
 */
import { mkdirSync, writeFileSync, copyFileSync, existsSync, readdirSync, readFileSync } from 'fs'
import { dirname, join, basename } from 'path'

const LIB_ROOT = 'public/library'
const TREE = { chassis: 'chassises', bark: 'barks', leaf: 'leaves', overlay: 'overlays' }
// the axis whose value names the canonical folder for each part-type
const PRIMARY_AXIS = { chassis: 'chassis.habit', bark: 'bark.type', leaf: 'leaf.silhouette', overlay: 'overlay.type' }

const canonicalValue = (part) => {
  const t = part.tags && part.tags[PRIMARY_AXIS[part.partType]]
  return (t && t.value) || '_unassigned'
}

export function canonicalDir(part) {
  return join(LIB_ROOT, TREE[part.partType] || part.partType, String(canonicalValue(part)), part.partId)
}

/**
 * place(part, opts) — write the canonical meta (+ optional binary copy) and
 * return the canonical dir. Idempotent (write-if-changed). `part.sourcePath` is
 * the original asset (a GLB / a pack dir / a Bark dir); we point at it.
 */
export function place(part, opts = {}) {
  const dir = canonicalDir(part)
  mkdirSync(dir, { recursive: true })
  const meta = {
    partId: part.partId,
    partType: part.partType,
    source: part.source,
    canonicalValue: canonicalValue(part),
    sourcePath: part.sourcePath || null,
    tags: part.tags,
    conformReport: part.conformReport || null,
  }
  writeIfChanged(join(dir, 'meta.json'), JSON.stringify(meta, null, 2) + '\n')
  // small, readable binary: copy the leaf card so leaves/<silhouette>/ is real.
  if (opts.copyBinaries && part.partType === 'leaf' && part.sourcePath) {
    const shape = join(part.sourcePath, 'shape.png')
    if (existsSync(shape)) copyFileSync(shape, join(dir, 'shape.png'))
  }
  return dir
}

/** Regenerate MANIFEST.json — the back-end "what's where, by rubric value" doc. */
export function regenerateManifest(parts) {
  const byTree = {}
  for (const p of parts) {
    const t = TREE[p.partType] || p.partType
    const v = String(canonicalValue(p))
    byTree[t] = byTree[t] || {}
    byTree[t][v] = byTree[t][v] || []
    byTree[t][v].push({ partId: p.partId, source: p.source, sourcePath: p.sourcePath || null })
  }
  const manifest = {
    _doc: 'Generated by library-builder.js (Forest Builder §4.5). Canonical part tree by rubric value. sourcePath points at the original asset (binaries not duplicated this stage).',
    generatedFrom: 'arborist/ingest.js',
    counts: Object.fromEntries(Object.entries(byTree).map(([t, vs]) => [t, Object.values(vs).reduce((n, a) => n + a.length, 0)])),
    tree: byTree,
  }
  mkdirSync(LIB_ROOT, { recursive: true })
  writeIfChanged(join(LIB_ROOT, 'MANIFEST.json'), JSON.stringify(manifest, null, 2) + '\n')
  return manifest
}

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return false
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  return true
}
