[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[realtime]
enabled = true

[auth]
enabled = true
site_url = "https://lafayette-square.com"

[auth.sms]
max_frequency = "60s"

[auth.external.apple]
enabled = false

[auth.external.google]
enabled = false
