#!/usr/bin/env node
/**
 * fetch-photos — bring every listing photograph onto our own server.
 *
 * ⛔⛔ HOTLINKING MAKES A LOCAL RESOURCE DEPEND ON THE PLATFORMS IT EXISTS TO REPLACE.
 * Ruled by Jacob, 2026-09-22: *"the whole idea is that we Do Not Support Facebook or
 * oligarchic social media channels and we are creating a local resource."* Measured on
 * huron at the time: of 63 images, **20 loaded from a platform CDN** — 13 Wix, 6 Shopify,
 * 1 Squarespace — and every one of those requests carries a `Referer` telling that
 * platform which card on the town's map a visitor is reading.
 *
 * ⛔⛔ AND THE SHARPER REASON, WHICH THIS TOWN SUPPLIED: A HOTLINKED IMAGE ON A LAPSED
 * DOMAIN IS AN INJECTION VECTOR. Huron gave us three local domains that lapsed and were
 * re-registered by squatters serving offshore casinos. Had any carried an image we
 * hotlinked, the squatter would control what renders on the town's map — under a credit
 * line still naming the business. A wrong LINK is visible in the data; a wrong IMAGE only
 * appears on screen.
 *
 * ⭐ THE TRADE, STATED PLAINLY: copying makes us the publisher of a copy. What makes that
 * defensible is the discipline around it, not the copying — only images an operator
 * published about themselves or that carry an explicit licence, a credit and a link back
 * on every one, and `source_url` preserved so the original is always one click away.
 * ⛔ THE ONE THING WE GIVE UP is that a business deleting its photo no longer removes it
 * from our card. That was a real protection and it is gone; takedown becomes a request to
 * the operator rather than an automatic consequence.
 *
 * ⛔ IT REFUSES RATHER THAN GUESSES: no credit, not an image, or a body that is not what
 * the content-type claims, and the file is skipped loudly. An uncredited photograph on a
 * card we host is the state this tool exists to prevent.
 *
 * ⭐⭐ TWO COPIES, AND THE SPLIT IS THE WHOLE DESIGN (Jacob, 2026-09-22: *"in the future
 * these things will all be stored on the client's server, we're just doing the best guess
 * first step"*).
 *
 *   ARCHIVE  `cartograph/data/<scene>/photos/<id>/NN.ext` — the bytes exactly as
 *            fetched, TRACKED and never deployed. ⛔ It sits BESIDE content/ and not under raw/, because raw/ is gitignored for
 *            huge re-fetchable intake (elevation tiles, OSM dumps) and these are the
 *            opposite: small and NOT re-fetchable. It is tracked rather than
 *            regenerable-on-demand because `source_url` is not a durable path back: this
 *            town produced three local domains that lapsed inside a year. When a client
 *            eventually hosts their own photographs, THIS is what we hand them, and a
 *            downscale we could not undo would have thrown away the only full-res copy in
 *            existence.
 *   WEB      `public/photos/<scene>/<id>/NN.jpg` — long edge ≤ 1600, derived, GITIGNORED,
 *            regenerated by this tool. A derived artifact does not belong in git, and the
 *            listing points here.
 *
 * ⛔ SO THE RESIZE IS NEVER DESTRUCTIVE. Before this split the fetch wrote one 8.5 MB file
 * into `public/` and the listing pointed at it: 68 MB shipped to visitors for 63 pictures,
 * and downscaling in place would have been irreversible. (Lafayette Square is the warning —
 * 884 MB across 297 files, median 1.1 MB, with no archive/web distinction at all.)
 *
 * ▶ node cartograph/fetch-photos.mjs --scene=huron [--dry]
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import { requireExplicitMap } from './scene.js'

const SCENE = requireExplicitMap('fetch-photos')
const DRY = process.argv.includes('--dry')
const ROOT = path.resolve(import.meta.dirname, '..')
const WEB = path.join(ROOT, 'public', 'photos', SCENE)
const ARCHIVE = path.join(ROOT, 'cartograph/data', SCENE, 'photos')
const LONG_EDGE = 1600        // a full-bleed card on a retina phone, and a laptop lightbox
const QUALITY = 82
const sharp = (await import('sharp')).default

// ⛔⛔ IT WRITES THE OVERRIDES, NOT JUST THE LISTINGS — and the first version did not,
// which cost the whole localisation. `content/listings.json` is DERIVED: `bake-content`
// rebuilds it from the Overture base plus `listings.overrides.json` on every run. Writing
// local paths only into the derived file meant the next re-bake (there were four that
// evening, each a publish) silently restored every hotlink, and the check caught it the
// following morning rather than the tool preventing it.
// ⭐ The rule this violated is the repo's own: a correction belongs in the overrides
// layer, where git reviews it and a fresh intake cannot destroy it. I wrote that sentence
// into host/README.md the same day and then did the opposite here.
const lp = path.join(ROOT, 'cartograph/data', SCENE, 'content/listings.json')
const op = path.join(ROOT, 'cartograph/data', SCENE, 'content/listings.overrides.json')
if (!existsSync(lp)) { console.error(`⛔ no content/listings.json for scene "${SCENE}"`); process.exit(2) }
const doc = JSON.parse(readFileSync(lp, 'utf8'))
const listings = Array.isArray(doc) ? doc : (doc.listings || [])
const overrides = existsSync(op) ? JSON.parse(readFileSync(op, 'utf8')) : null
// A listing's photos may live under several GERS keys (a duplicate pair); rewrite each.
const patchesFor = (listingName) => !overrides ? []
  : Object.values(overrides.patches || {}).filter(p => p._match_name === listingName && Array.isArray(p.photos))

const EXT = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp', 'image/gif': 'gif', 'image/svg+xml': 'svg', 'image/avif': 'avif' }
// ⛔ The bytes must agree with the header. A server can label an HTML error page
// `image/jpeg`, and a 43 KB "for sale" page stored as a photo would render as a broken
// tile with a real business's credit under it.
const MAGIC = [
  [[0xFF, 0xD8, 0xFF], 'jpg'], [[0x89, 0x50, 0x4E, 0x47], 'png'], [[0x47, 0x49, 0x46], 'gif'],
]
const sniff = (buf) => {
  for (const [sig, kind] of MAGIC) if (sig.every((b, i) => buf[i] === b)) return kind
  const head = buf.subarray(0, 64).toString('latin1')
  if (buf.subarray(0, 4).toString('latin1') === 'RIFF' && buf.subarray(8, 12).toString('latin1') === 'WEBP') return 'webp'
  if (/^\s*<(\?xml|svg)/i.test(head)) return 'svg'
  if (/^\s*<(!doctype|html)/i.test(head)) return null      // an HTML page wearing an image's content-type
  return 'other'
}

let fetched = 0, kept = 0, skipped = 0, bytes = 0, archived_bytes = 0
const problems = []

// ⛔ SVG IS PASSED THROUGH UNTOUCHED — it is already resolution-independent, and rastering a
// wordmark to 1600px would make it worse and bigger at once. Everything else becomes a JPEG
// at the long edge, never upscaled: a picture smaller than the cap is already web-sized and
// re-encoding it only loses information.
async function derive(srcPath, outDir, stem) {
  mkdirSync(outDir, { recursive: true })
  if (srcPath.endsWith('.svg')) {
    const out = `${stem}.svg`
    if (!existsSync(path.join(outDir, out))) writeFileSync(path.join(outDir, out), readFileSync(srcPath))
    return out
  }
  const out = `${stem}.jpg`
  const dest = path.join(outDir, out)
  if (existsSync(dest)) return out
  await sharp(srcPath)
    .rotate()                                   // honour EXIF orientation before resizing
    .resize({ width: LONG_EDGE, height: LONG_EDGE, fit: 'inside', withoutEnlargement: true })
    .jpeg({ quality: QUALITY, mozjpeg: true })
    .toFile(dest)
  return out
}

for (const l of listings) {
  const photos = l.photos || []
  if (!photos.length) continue
  for (let i = 0; i < photos.length; i++) {
    const p = photos[i]
    const entry = typeof p === 'string' ? { url: p } : { ...p }
    const src = entry.source_url || entry.url
    if (!src || src.startsWith('/')) { kept++; continue }   // already ours

    // ⛔ A photograph we HOST without a credit is worse than one we merely link, because
    // hosting asserts a right we may not have. No credit, no copy.
    if (!entry.credit) { skipped++; problems.push(`${l.name}: no credit on ${src} — not copied`); continue }

    const adir = path.join(ARCHIVE, l.id)
    const wdir = path.join(WEB, l.id)
    const stem = String(i + 1).padStart(2, '0')
    const archived = existsSync(adir) && readdirSync(adir).find(f => f.startsWith(stem + '.'))
    if (archived) {
      const web = await derive(path.join(adir, archived), wdir, stem)
      entry.source_url = src
      entry.url = `/photos/${SCENE}/${l.id}/${web}`
      photos[i] = entry; kept++; bytes += statSync(path.join(wdir, web)).size
      continue
    }
    if (DRY) { fetched++; continue }

    let res, buf
    try {
      res = await fetch(src, { redirect: 'follow', headers: { 'User-Agent': 'TheWard/1.0 (+town directory; contact via listing)' } })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      buf = Buffer.from(await res.arrayBuffer())
    } catch (e) { skipped++; problems.push(`${l.name}: ${src} — ${e.message}`); continue }

    const kind = sniff(buf)
    if (kind === null) { skipped++; problems.push(`${l.name}: ${src} served an HTML page under content-type ${res.headers.get('content-type')} — not copied`); continue }
    const ct = (res.headers.get('content-type') || '').split(';')[0].trim()
    const ext = EXT[ct] || (kind !== 'other' ? kind : null)
    if (!ext) { skipped++; problems.push(`${l.name}: ${src} is content-type ${ct || '(none)'}, not a known image`); continue }

    mkdirSync(adir, { recursive: true })
    const file = `${stem}.${ext}`
    writeFileSync(path.join(adir, file), buf)    // the archive keeps the bytes as fetched
    const web = await derive(path.join(adir, file), wdir, stem)
    entry.source_url = src                       // ⭐ the only surviving record of the origin
    entry.url = `/photos/${SCENE}/${l.id}/${web}`
    photos[i] = entry
    fetched++; bytes += statSync(path.join(wdir, web)).size; archived_bytes += buf.length
  }
}

// ⭐ Mirror the rewritten photo arrays back into the durable layer, matched by the
// ORIGINAL url so a re-run or a partial run cannot mis-pair them.
let patched = 0
if (!DRY && overrides) {
  for (const l of listings) {
    for (const pt of patchesFor(l.name)) {
      pt.photos = pt.photos.map((op_) => {
        const src = typeof op_ === 'string' ? op_ : (op_.source_url || op_.url)
        const now = (l.photos || []).find(np => np && (np.source_url === src || np.url === src))
        if (!now || typeof now === 'string') return op_
        patched++
        return { ...(typeof op_ === 'string' ? {} : op_), url: now.url, source_url: now.source_url }
      })
    }
  }
  writeFileSync(op, JSON.stringify(overrides, null, 2) + '\n')
}
if (!DRY) writeFileSync(lp, JSON.stringify(doc, null, 1) + '\n')
console.log(`  ${fetched} fetched · ${kept} already archived · ${skipped} refused`)
console.log(`  web (ships): ${(bytes / 1e6).toFixed(1)} MB · archive: ${((archived_bytes || du(ARCHIVE)) / 1e6).toFixed(1)} MB`)
if (!DRY) console.log(`  ${patched} photo url(s) written back to listings.overrides.json — so a re-bake cannot restore the hotlinks`)
if (problems.length) {
  console.log(`  ⛔ ${problems.length} refused, each for a stated reason:`)
  for (const m of problems.slice(0, 12)) console.log(`     ${m}`)
  if (problems.length > 12) console.log(`     …and ${problems.length - 12} more`)
}
if (DRY) console.log('  (dry run — nothing written)')

function du(dir) {
  if (!existsSync(dir)) return 0
  let n = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name)
    n += e.isDirectory() ? du(f) : statSync(f).size
  }
  return n
}
